deals/urls.py
from django.urls import path
from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.dealsMainView , name='deals'),
    path('old_deals/', views.oldDeals , name='old_deals'),
    path('register_new_deal/', views.registerNewDeal , name='register_new_deal'),
    path('edit_deals/<int:id>/', views.editDeal , name='edit_deals'),
    path('terminate_or_end_deals/<int:id>/<str:endOrTerminate>/', views.terminateOrEndDeals , name='terminate_or_end_deals'),
    
]

finance/urls.py
from django.urls import path
from . import views

app_name = 'finance'

urlpatterns = [
    path('', views.seeSalary , name='see_salary'),
    path('see_salaries_in_details/', views.seeSalaryInDetails , name='see_salaries_in_details'),
    path('update_salary/', views.updateSalary , name='update_salary'),
    path('create_monthly_salary/', views.createSelaryStatus , name='create_monthly_salary'),
    path('make_employee_salary_paid/<int:id>', views.makeEmployeeSalaryPaid , name='make_employee_salary_paid'),
    path('accounts/', views.accountsMainView , name='accounts'),
    path('accounts_spend_money/', views.addSpendMoney , name='accounts_spend_money'),
    path('edit_spend_entry/<int:id>', views.editSpendMoney , name='edit_spend_entry'),
    path('edit_recived_entry/<int:id>', views.editRecivedMoney , name='edit_recived_entry'),
    path('delete_spend_entry/<int:id>', views.deleteSpendMoney , name='delete_spend_entry'),
    path('delete_recived_entry/<int:id>', views.deleteRecivedMoney , name='delete_recived_entry'),
    path('entity_register/', views.registerEntity , name='entity_register'),
    path('see_entity_to_edit/', views.seeAllEntry , name='see_entity_to_edit'),
    path('entity_edit/<int:id>', views.editEntity , name='entity_edit'),
    
]

minErp/urls.py
from django.contrib import admin
from django.urls import path, include

from userAuth import views

from django.conf import settings
from django.conf.urls import handler404
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('auth/', include('userAuth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('finance/', include('finance.urls')),
    path('deals/', include('deals.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'userAuth.views.notFound'

finance/models.py
from django.db import models
from django.contrib.auth.models import User
from userAuth.models import userInfo

# Create your models here.

class salary(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    salary = models.IntegerField()



class paidUnpaidSalaryStatus(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    monthlySalary = models.IntegerField()
    month = models.DateField()
    paidStatus = models.BooleanField()



class clientAndServiceProvider(models.Model):

    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    occupation = models.CharField(max_length=50, blank=True)
    companyName = models.CharField(max_length=50, blank=True)
    isClient = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.name + ' (' + self.companyName + ')'



class recivedMoney(models.Model):

    recivedFrom = models.ForeignKey(clientAndServiceProvider, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField()
    purpose = models.CharField(max_length=50)
    medium = models.CharField(max_length=30)

    
    

class spendMoney(models.Model):

    spendOn = models.ForeignKey(clientAndServiceProvider, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField()
    purpose = models.CharField(max_length=50)
    medium = models.CharField(max_length=30)


    

finance/forms.py
from django import forms
from .models import clientAndServiceProvider
from userAuth import models


class registerEntity(forms.ModelForm):
    isClient = forms.BooleanField(label='Is this entity a client', required=False)
    class Meta():
        model = clientAndServiceProvider
        fields = ('isClient', 'name', 'phone', 'email', 'occupation', 'companyName' )

finance/views.py
from django.shortcuts import render
from django.db.models import Q

from userAuth import models
from .models import salary, paidUnpaidSalaryStatus, clientAndServiceProvider, recivedMoney, spendMoney

from . import forms

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

import datetime

# Create your views here.


@login_required
def seeSalary(request):
    
    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk=currentUser.id)

    dict = {}

    if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "2" or currentUserMoreInfo.role == "3" ):
        dict.update({"employeeController": True})

    if (currentUserMoreInfo.role == "1"):
        dict.update({"fullEmployeeControler": True})

    if currentUserMoreInfo.role == '1' or currentUserMoreInfo.role == '4':

        salaryAndUser = models.User.objects.values( 'id', 'first_name', 'last_name', 'userinfo__role', 'salary__salary', 'salary__id').order_by('userinfo__role')
        dict.update({"finaceController": True})
        dict.update({'salaryAndUser': salaryAndUser})


    return render(request, 'finance/seeSalary.html', context=dict)




@login_required
def seeSalaryInDetails(request):

    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk=currentUser.id)

    dict = {}

    if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "2" or currentUserMoreInfo.role == "3" ):
        dict.update({"employeeController": True})

    if (currentUserMoreInfo.role == "1"):
        dict.update({"fullEmployeeControler": True})


    if currentUserMoreInfo.role == '1' or currentUserMoreInfo.role == '4':

        user = models.User.objects.all()

        salaryAndUser = paidUnpaidSalaryStatus.objects.all()

        dict.update({"finaceController": True})
        dict.update({'salaryAndUser': salaryAndUser})

    return render(request, 'finance/employeeSalaries.html', context=dict)




@login_required
def updateSalary(request):

    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk = currentUser.id)

    if (currentUserMoreInfo.role == '1') or (currentUserMoreInfo.role == '4'):
        if request.method == "POST":

            employeeId = request.POST.get("id")
            salaryId = request.POST.get("salaryid")
            employeeSalary = request.POST.get("salary")

            employee = models.User.objects.get(pk=employeeId)

            if salary.objects.filter(user=employee):
                newSalary = salary.objects.get(user=employee)
                newSalary.salary = employeeSalary
                newSalary.save()
            else:
                newSalary = salary(user=employee, salary=employeeSalary)
                newSalary.save()

    return HttpResponseRedirect(reverse('finance:see_salary'))
    
    


@login_required
def createSelaryStatus(request):

    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk = currentUser.id)

    dict = {}

    if (currentUserMoreInfo.role == '1') or (currentUserMoreInfo.role == '4'):
        dict.update({"finaceController": True})

        today = datetime.datetime.now()

        startDate = datetime.datetime(today.year, today.month, 1)
        endDate = ''
        if (today.month==2):
            endDate = datetime.datetime(today.year, today.month, 28)
        elif (today.month == 4) or (today.month == 6) or (today.month == 9) or (today.month == 11):
            endDate = datetime.datetime(today.year, today.month, 30)
        else:
            endDate = datetime.datetime(today.year, today.month, 31)


        monthlySelary = paidUnpaidSalaryStatus.objects.filter(month__range=[startDate, endDate])
        monthlySelaryCount = monthlySelary.count()


        userWithRole = models.userInfo.objects.all()
        userWithRoleCount = userWithRole.count()

        checking = True

        for salaryInMonth in monthlySelary:
            employeePayable = salary.objects.get(user=salaryInMonth.user)

            if salaryInMonth.monthlySalary!=employeePayable.salary:
                salaryInMonth.monthlySalary = employeePayable.salary
                salaryInMonth.paidStatus = False
                salaryInMonth.save()
                checking = False


        if monthlySelaryCount and checking:
            dict.update({'message': 'Already Created.You can not pay the employeese that joined in this month.'})
            return render(request, 'showMessage.html', context=dict)

        if monthlySelaryCount and (checking==False):
            dict.update({'message': 'Salary Sheet successfully updated.'})
            return render(request, 'showMessage.html', context=dict)


        monthlySalaryAndUser = models.User.objects.values( 'id', 'first_name', 'last_name', 'userinfo__role', 'salary__salary', 'salary__id').order_by('userinfo__role')

        for user in monthlySalaryAndUser:



            if(user['userinfo__role']):

                employee = models.User.objects.get(pk=user['id'])
                employeeSalary = user['salary__salary']

                newSalaryEntry = paidUnpaidSalaryStatus(user=employee)
                newSalaryEntry.monthlySalary = employeeSalary
                newSalaryEntry.month = datetime.datetime.now()
                newSalaryEntry.paidStatus = False
                newSalaryEntry.save()


        dict.update({'message': 'Salary Sheet created successfully.'})
        dict.update({"finaceController": True})
        return render(request, 'showMessage.html', context=dict)



    dict = {'message': 'You are not from finance'}
    return render(request, 'showMessage.html', context=dict)



@login_required
def makeEmployeeSalaryPaid(request, id):

    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk = currentUser.id)

    if (currentUserMoreInfo.role == '1') or (currentUserMoreInfo.role == '4'):

        monthlyEmployeeSelary = paidUnpaidSalaryStatus.objects.get(pk=id)
        monthlyEmployeeSelary.paidStatus = True
        monthlyEmployeeSelary.save()

        return HttpResponseRedirect(reverse('finance:see_salaries_in_details'))


    dict = {'message': 'You are not from finance'}
    return render(request, 'showMessage.html', context=dict)











@login_required
def accountsMainView(request):

    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk = currentUser.id)

    if (currentUserMoreInfo.role == '1') or (currentUserMoreInfo.role == '4'):
        dict = {'finaceController': True}
        recivedAmount = 0
        spendAmount = 0

        recivedEntries = ''
        spendEntries = ''
        
        recivedEntries = recivedMoney.objects.all().order_by('-date')
        dict.update({'recivedEntries': recivedEntries})

        for money in recivedEntries:
            recivedAmount += money.amount

        spendEntries = spendMoney.objects.all().order_by('-date')
        dict.update({'spendEntries': spendEntries})

        for money in spendEntries:
            spendAmount += money.amount

        currentBalance = recivedAmount-spendAmount


        searchName = request.GET.get('name')
        startDate = request.GET.get('startDate')
        endDate = request.GET.get('endDate')

        if (searchName and startDate and endDate) or (searchName and startDate) or (searchName and endDate):
            if not endDate:
                endDate = datetime.datetime.now()

            if not startDate:
                startDate = datetime.datetime(2000, 1, 1)

            recivedEntries = recivedMoney.objects.filter(Q(recivedFrom__name__icontains=searchName) | Q(recivedFrom__email__icontains=searchName) | Q(recivedFrom__companyName__icontains=searchName)).filter(date__range=[startDate, endDate]).order_by('-date')
            recivedAmount = 0
            for money in recivedEntries:
                recivedAmount += money.amount

            spendEntries = spendMoney.objects.filter(Q(spendOn__name__icontains=searchName) | Q(spendOn__email__icontains=searchName) | Q(spendOn__companyName__icontains=searchName)).filter(date__range=[startDate, endDate]).order_by('-date')
            spendAmount = 0
            for money in spendEntries:
                spendAmount += money.amount

        elif searchName:
            recivedEntries = recivedMoney.objects.filter(Q(recivedFrom__name__icontains=searchName) | Q(recivedFrom__email__icontains=searchName) | Q(recivedFrom__companyName__icontains=searchName)).order_by('-date')
            recivedAmount = 0
            for money in recivedEntries:
                recivedAmount += money.amount

            spendEntries = spendMoney.objects.filter(Q(spendOn__name__icontains=searchName) | Q(spendOn__email__icontains=searchName) | Q(spendOn__companyName__icontains=searchName)).order_by('-date')
            spendAmount = 0
            for money in spendEntries:
                spendAmount += money.amount

        elif startDate and endDate:
            recivedEntries = recivedMoney.objects.filter(date__range=[startDate, endDate]).order_by('-date')
            recivedAmount = 0
            for money in recivedEntries:
                recivedAmount += money.amount

            spendEntries = spendMoney.objects.filter(date__range=[startDate, endDate]).order_by('-date')
            spendAmount = 0
            for money in spendEntries:
                spendAmount += money.amount

        elif startDate:
            endDate = datetime.datetime.now()
            recivedEntries = recivedMoney.objects.filter(date__range=[startDate, endDate]).order_by('-date')
            recivedAmount = 0
            for money in recivedEntries:
                recivedAmount += money.amount

            spendEntries = spendMoney.objects.filter(date__range=[startDate, endDate]).order_by('-date')
            spendAmount = 0

templates/finance/accountsMain.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block nav_block %} {% if
finaceController %} {% endif %} {% endblock %} {% block body_block %} {% if
user.is_authenticated %}

<style>
  td {
    min-width: 85px;
  }

  input[type="text"],
  input[type="number"],
  input[type="email"],
  input[type="password"],
  input[type="url"] {
    border: 0px;
    border-bottom: 1px solid black;
  }

  input[type="text"]:active,
  input[type="number"]:active,
  input[type="email"]:active,
  input[type="password"]:active,
  input[type="url"]:active {
    border-bottom: 2px solid black;
    outline: 0px;
  }

  input[type="text"]:focus,
  input[type="number"]:focus,
  input[type="email"]:focus,
  input[type="password"]:focus,
  input[type="url"]:focus {
    border-bottom: 2px solid black;
    outline: 0px solid black;
  }

  input[type="date"] {
    border: 0px solid white;
    border-bottom: 1px solid black;
  }

  input[type="date"]:focus {
    outline: 0px;
    border-bottom: 2px solid black;
  }

  input[type="date"]:active {
    outline: 0px;
    border-bottom: 2px solid black;
  }

  select {
    border: #ffffff;
    border-bottom: 0px solid black;
  }
  select:focus {
    border: #ffffff;
    outline: 0;
    border-bottom: 2px solid black;
  }
  select:active {
    border: #ffffff;
    border-bottom: 2px solid black;
  }

  .leftMargine {
    margin-left: 20px;
  }

  .wrapper {
    margin-top: 20px;
    margin-bottom: 20px;
    min-height: 80vh;
  }

  .spendAccount {
    display: none;
    margin-bottom: 40px;
  }

  .recivedAccount {
    margin-bottom: 40px;
  }

  #filterByDate,
  #filterByName,
  #filterByBoth {
    display: none;
  }
</style>

<div class="wrapper container">
  <div class="row mt-3">
    <div class="col-lg-8 col-sm-12 g">
      <div class="text-left mt-3">
        <button class="btn btn-outline-info mr-2 mt-2" id="applyFilterByDate">
          Filter by Date
        </button>
        <button class="btn btn-outline-info mr-2 mt-2" id="applyFilterByName">
          Filter by Name
        </button>
        <button class="btn btn-outline-info mr-2 mt-2" id="applyFilterByBoth">
          Filter by Both
        </button>
        <a
          class="btn btn-outline-info mr-2 mt-2"
          href="{% url 'finance:accounts' %}"
          id="resetFilter"
          >Reset Filter</a
        >
      </div>
    </div>

    <div class="col-lg-4 mt-3">
      <a
        href="{% url 'finance:entity_register' %}"
        class="btn btn-primary mr-2"
      >
        Add New Entity
      </a>

      <a href="{% url 'finance:see_entity_to_edit' %}" class="btn btn-primary">
        Edit Entity
      </a>
    </div>
  </div>

  <div class="filters">
    <div id="filterByName">
      <form action="{% url 'finance:accounts' %}" method="GET">
        <label for="name">Name: </label>
        <input
          type="text"
          name="name"
          id="name"
          style="display: inline-block; width: auto"
        />
        <input type="submit" value="Submit" />
      </form>
    </div>

    <div id="filterByDate">
      <form action="" method="GET">
        <label for="startDate">Start Date: </label>
        <input type="date" name="startDate" id="startDate" />
        <label for="endDate">End Date: </label>
        <input type="date" name="endDate" id="endDate" />
        <input type="submit" value="Submit" />
      </form>
    </div>

    <div id="filterByBoth">
      <form action="" method="GET">
        <label for="startDate">Start Date: </label>
        <input type="date" name="startDate" id="startDate" />
        <label for="endDate">End Date: </label>
        <input type="date" name="endDate" id="endDate" />
        <label for="name">Name: </label>
        <input
          type="text"
          name="name"
          id="name"
          style="display: inline-block; width: auto"
        />
        <input type="submit" value="Submit" />
      </form>
    </div>
  </div>

  <h1 style="margin: 40px 0 10px">Current Balance: {{ currentBalance }}</h1>
  <button class="btn btn-success" id="changeVisibility">Spend Money</button>

  <div class="recivedAccount" style="width: 100%; overflow-x: scroll">
    <h2>Recived Account:</h2>

    <form action="{% url 'finance:accounts' %}" method="POST" id="recivedForm">
      <table style="margin-bottom: 0">
        <tr>
          <th>Date</th>
          <th>Entity</th>
          <th>Amount</th>
          <th>Purpose</th>
          <th>Medium</th>
          <th>Action</th>
        </tr>

        <tr>
          <td colspan="2"><b> Total </b></td>
          <td><b> {{ recivedAmount }} </b></td>
          <td colspan="3">If a user does not exist then create one.</td>
        </tr>

        <tr>
          <td>
            <input type="date" name="date" required value="{% now 'Y-m-d' %}" />
          </td>
          <td>
            <select name="user" required>
              {% for client in clients %}
              <option value="{{ client.id }}">
                {{ client.name }} ({{ client.companyName }})
              </option>
              {% endfor %}
            </select>
          </td>
          <td><input type="number" name="amount" required /></td>
          <td><input type="text" name="purpose" required /></td>
          <td><input type="text" name="medium" required /></td>

          <td>
            {% csrf_token %}
            <input type="submit" value="add" style="margin: 0" />
          </td>
        </tr>

        {% for entry in recivedEntries %}
        <tr>
          <td>{{ entry.date }}</td>
          <td>
            {{ entry.recivedFrom.name }} {% if entry.recivedFrom.companyName %}
            ( {{ entry.recivedFrom.companyName }} ) {% endif %}
          </td>
          <td>{{ entry.amount }}</td>
          <td>{{ entry.purpose }}</td>
          <td>{{ entry.medium }}</td>
          <td>
            <span class="editEntry" style="border: 0; margin: 0 10px 0 10px">
              <a href="{% url 'finance:edit_recived_entry' id=entry.id %}">
                <img
                  src="{% static 'images/icons/edit.png' %}"
                  alt="edit"
                  width="15px"
                />
              </a>
            </span>
            <span class="deleteEntry" style="border: 0; margin-right: 10px">
              <a
                href="{% url 'finance:delete_recived_entry' id=entry.id %}"
                onclick="return confirm('Are you sure?')"
              >
                <img
                  src="{% static 'images/icons/delete.png' %}"
                  alt="delete"
                  width="15px"
                />
              </a>
            </span>
          </td>
        </tr>
        {% endfor %}
      </table>
    </form>
  </div>

  <div class="spendAccount" style="width: 100%; overflow-x: scroll">
    <h2>Spend Account:</h2>

    <form action="{% url 'finance:accounts_spend_money' %}" method="POST">
      <table style="margin-bottom: 0">
        <tr>
          <th>Date</th>
          <th>Entity</th>
          <th>Amount</th>
          <th>Purpose</th>
          <th>Medium</th>
          <th>Action</th>
        </tr>

        <tr>
          <td colspan="2"><b> Total </b></td>
          <td><b> {{ spendAmount }} </b></td>
          <td colspan="3">If a user does not exist then create one.</td>
        </tr>

        <tr>
          <td>
            <input type="date" name="date" required value="{% now 'Y-m-d' %}" />
          </td>
          <td>
            <select name="user" required>
              {% for client in clients %}
              <option value="{{ client.id }}">
                {{ client.name }} ({{ client.companyName }})
              </option>
              {% endfor %}
            </select>
          </td>
          <td><input type="number" name="amount" required /></td>
          <td><input type="text" name="purpose" required /></td>
          <td><input type="text" name="medium" required /></td>
          <td>
            {% csrf_token %}
            <input type="submit" value="add" style="margin: 0" />
          </td>
        </tr>

        {% for entry in spendEntries %}
        <tr>
          <td>{{ entry.date }}</td>
          <td>
            {{ entry.spendOn.name }} {% if entry.spendOn.companyName %} ( {{
            entry.spendOn.companyName }} ) {% endif %}
          </td>
          <td>{{ entry.amount }}</td>
          <td>{{ entry.purpose }}</td>
          <td>{{ entry.medium }}</td>
          <td>
            <span class="editEntry" style="border: 0; margin: 0 10px 0 10px">
              <a href="{% url 'finance:edit_spend_entry' id=entry.id %}">
                <img
                  src="{% static 'images/icons/edit.png' %}"
                  alt="edit"
                  width="15px"
                />
              </a>
            </span>
            <span class="deleteEntry" style="border: 0; margin-right: 10px">
              <a
                href="{% url 'finance:delete_spend_entry' id=entry.id %}"
                onclick="return confirm('Are you sure?')"
              >
                <img
                  src="{% static 'images/icons/delete.png' %}"
                  alt="delete"
                  width="15px"
                />
              </a>
            </span>
          </td>
        </tr>
        {% endfor %}
      </table>
    </form>
  </div>

  <script src="{% static 'js/showRecivedAndSpend.js' %}"></script>
</div>

{% endif %} {% endblock %}

templates/finance/employeeSalaries.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block nav_block %} {% if
finaceController %} {% endif %} {% endblock %} {% block body_block %} {% if
user.is_authenticated %}

<style>
  .wrapper {
    margin-top: 20px;
    margin-bottom: 20px;
    min-height: 80vh;
  }
</style>

<div class="container wrapper">
  <a
    href="{% url 'finance:create_monthly_salary' %}"
    class="buttonStyle1"
    style="padding: 5px 30px"
    >Create This month's Salary Sheet</a
  >

  <h1 style="margin: 20px 0">Employee Salary list in details:</h1>

  <div style="width: 100%; overflow-x: scroll">
    <table>
      <tr>
        <th>Name</th>
        <th>Salary</th>
        <th>month</th>
        <th>Status</th>
      </tr>

      {% for user in salaryAndUser %}

      <tr>
        <td>
          {{ user.user.first_name }} {{ user.user.last_name }} {% if
          user.user.userinfo.role == '1' %} ( Chief ) {% elif
          user.user.userinfo.role == '2' %} ( Moderator ) {% elif
          user.user.userinfo.role == '3' %} ( HR ) {% elif
          user.user.userinfo.role == '4' %} ( Accountant ) {% else %} ( Office
          Employee ) {% endif %}
        </td>
        <td>{{ user.monthlySalary }}</td>
        <td>{{ user.month|date:"M Y" }}</td>
        <td>
          {% if user.paidStatus %} Paid {% else %} Unpaid
          <a
            href="{% url 'finance:make_employee_salary_paid' id=user.id %}"
            class="buttonStyle1"
            >Make Paid</a
          >
          {% endif %}
        </td>
      </tr>

      {% endfor %}
    </table>
  </div>
</div>

{% endif %} {% endblock %}

templates/finance/seeSpendMoney.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block nav_block %} {% if
finaceController %} {% endif %} {% endblock %} {% block body_block %} {% if
user.is_authenticated %}

<style>
  .leftMargine {
    margin-left: 20px;
  }

  .wrapper {
    margin-top: 20px;
    margin-bottom: 20px;
    min-height: 80vh;
  }

  .left,
  .right {
    margin: 20px;
  }
</style>

<div class="wrapper container">
  <div style="margin-top: 30px">
    <a
      href="{% url 'finance:entity_register' %}"
      class="btn btn-primary leftMargine"
      style="float: right"
      >Add New Entity</a
    >

    <a
      href="{% url 'finance:see_entity_to_edit' %}"
      class="btn btn-primary leftMargine"
      style="float: right"
      >Edit Entity</a
    >

    <a
      href="{% url 'finance:accounts' %}"
      class="btn btn-success"
      style="float: left"
      >Recived Money</a
    >
    <br />
  </div>

  <div class="recivedAccount">
    <h2 style="margin: 20px 0">Spend Money: {{ totalAmount }}</h2>

    <form action="{% url 'finance:accounts_spend_money' %}" method="POST">
      <table style="margin-bottom: 0">
        <tr>
          <th>Date</th>
          <th>Entity</th>
          <th>Amount</th>
          <th>Purpose</th>
          <th>Medium</th>
        </tr>

        <tr>
          <td colspan="2"><b> Total </b></td>
          <td><b> {{ totalAmount }} </b></td>
          <td colspan="2">If a user does not exist then create one.</td>
        </tr>

        {% for entry in entries %}
        <tr>
          <td>{{ entry.date }}</td>
          <td>
            {{ entry.recivedFrom.name }} {% if entry.recivedFrom.companyName %}
            ( {{ entry.recivedFrom.companyName }} ) {% endif %}
          </td>
          <td>{{ entry.amount }}</td>
          <td>{{ entry.purpose }}</td>
          <td>{{ entry.medium }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td><input type="date" name="date" /></td>
          <td>
            <select name="user">
              {% for client in clients %}
              <option value="{{ client.id }}">
                {{ client.name }} ({{ client.companyName }})
              </option>
              {% endfor %}
            </select>
          </td>
          <td><input type="number" name="amount" /></td>
          <td><input type="text" name="purpose" /></td>
          <td><input type="text" name="medium" /></td>

          {% csrf_token %}
        </tr>
      </table>

      <div class="makeMiddle">
        <input type="submit" value="Add" />
      </div>
    </form>
  </div>

  <div class="spendAccount">
    <h2 style="margin: 20px 0">Spend Money: {{ totalAmount }}</h2>

    <form action="{% url 'finance:accounts_spend_money' %}" method="POST">
      <table style="margin-bottom: 0">
        <tr>
          <th>Date</th>
          <th>Entity</th>
          <th>Amount</th>
          <th>Purpose</th>
          <th>Medium</th>
        </tr>

        <tr>
          <td colspan="2"><b> Total </b></td>
          <td><b> {{ totalAmount }} </b></td>
          <td colspan="2">If a user does not exist then create one.</td>
        </tr>

        {% for entry in entries %}
        <tr>
          <td>{{ entry.date }}</td>
          <td>
            {{ entry.recivedFrom.name }} {% if entry.recivedFrom.companyName %}
            ( {{ entry.recivedFrom.companyName }} ) {% endif %}
          </td>
          <td>{{ entry.amount }}</td>
          <td>{{ entry.purpose }}</td>
          <td>{{ entry.medium }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td><input type="date" name="date" /></td>
          <td>
            <select name="user">
              {% for client in clients %}
              <option value="{{ client.id }}">
                {{ client.name }} ({{ client.companyName }})
              </option>
              {% endfor %}
            </select>
          </td>
          <td><input type="number" name="amount" /></td>
          <td><input type="text" name="purpose" /></td>
          <td><input type="text" name="medium" /></td>

          {% csrf_token %}
        </tr>
      </table>

      <div class="makeMiddle">
        <input type="submit" value="Add" />
      </div>
    </form>
  </div>
</div>

{% endif %} {% endblock %}