dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboardMainView , name='dashboard'),
    path('edit_profile/<int:id>/', views.editProfile , name='edit_profile'),
    path('createNotice/', views.createNotice , name='createNotice'),
    path('edit_notice/<int:id>/', views.editNotice , name='edit_notice'),
    path('make_complete/<int:id>/', views.makeComplete , name='make_complete'),
    path('make_incomplete/<int:id>/', views.makeIncomplete , name='make_incomplete'),
    path('delete_notice/<int:id>/', views.deleteNotice , name='delete_notice'),
    path('seeAllEmployee/', views.seeAllEmployee , name='seeAllEmployee'),
]

deals/urls.py
from django.urls import path
from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.dealsMainView , name='deals'),
    path('old_deals/', views.oldDeals , name='old_deals'),
    path('register_new_deal/', views.registerNewDeal , name='register_new_deal'),
    path('edit_deals/<int:id>/', views.editDeal , name='edit_deals'),
    path('terminate_or_end_deals/<int:id>/<str:endOrTerminate>/', views.terminateOrEndDeals , name='terminate_or_end_deals'),
    
]

minErp/urls.py
from django.contrib import admin
from django.urls import path, include

from userAuth import views

from django.conf import settings
from django.conf.urls import handler404
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('auth/', include('userAuth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('finance/', include('finance.urls')),
    path('deals/', include('deals.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'userAuth.views.notFound'

userAuth/urls.py
from django.urls import path
from . import views
from dashboard import views as dviews


app_name = 'userAuth'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', dviews.dashboardMainView, name='dashboard'),
    path('register/', views.userRegistration, name='userRegistation'),
    path('employee_delete/<int:id>', views.employeeDelete, name='employee_delete'),
    path('login/', views.loginApp, name='loginApp'),
    path('logout/', views.logoutApp, name='logoutApp'),
]

templates/authentication/deleteUser.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block nav_block %} {% if
showAddEmployees %}

<li class="nav-item">
  <a
    href="{% url 'userAuth:userRegistation' %}"
    class="nav-link"
    style="margin-left: 20px"
    >Add employees</a
  >
</li>

{% endif %} {% endblock %} {% block body_block %}

<style>
  input[type="submit"] {
    background-color: white;
    color: #f02e2e;
  }

  input[type="submit"]:hover {
    background-color: #f02e2e;
    color: white;
  }

  .message {
    margin-top: 10px;
    margin-bottom: 20px;
  }

  .mostOuterDiv {
    min-height: 75vh;
  }
</style>

<div class="selfMiddle container mostOuterDiv" style="margin-top: 30px">
  {% if user.is_authenticated %} {% if showMessage %}

  <h1 class="message">{{ message }}</h1>

  {% else %}

  <div class="makeMiddle">
    <img
      src="/media/{{ userMoreInfo.proPic }}"
      alt="Profile Pic"
      class="proPic"
    />

    <h2>{{ user.first_name }} {{ user.last_name }}</h2>

    <p>username: ( {{ user.username }} )</p>

    <p>Working as: {{ userMoreInfo.role }}</p>

    <p>{{ user.email }}</p>

    <a href="tel:{{ userMoreInfo.phone }}"> {{ userMoreInfo.phone }} </a>

    <form
      method="POST"
      action="{% url 'userAuth:employee_delete' id=user.id %}"
    >
      {% csrf_token %}
      <input
        type="submit"
        value="Delete"
        name="confirm"
        class="btn btn-danger"
      />
    </form>
  </div>

  {% endif %} {% endif %}
</div>

{% endblock %}

templates/authentication/editUser.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block body_block %}

<style>
  .formContainer {
    min-height: 72.1vh;
    width: 70%;
  }
</style>

<div class="container" style="margin-top: 30px">
  {% if showMessage %}

  <div class="makeMiddle">
    <h1 style="margin-top: 20px">{{ message }}</h1>
  </div>

  {% else %}

  <div class="formContainer">
    <h3 style="color: red">{{ alertMessage }}</h3>
    <form method="POST" enctype="multipart/form-data">
      {{ userform.as_p }} {% for field in userform2 %}

      <div>
        {% if field.label == 'Role' and not changeRole %}

        <p style="color: red; margin-top: 10px">You can not change role</p>

        {% else %}

        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {{ field }} {% endif %}
      </div>

      {% endfor %} {% csrf_token %}

      <div class="makeMiddle mt-4 mb-4">
        <input type="submit" value="Update" />
      </div>
    </form>
  </div>

  {% endif %}
</div>

{% endblock %}

templates/authentication/loginApp.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block body_block %}

<style>
  .wrapper {
    min-width: 75vh;
  }
</style>

{% if user.is_authenticated %}

<div
  class="makeMiddle justify-content-center align-items-center"
  style="padding-top: 150px; min-height: 80vh"
>
  <h1>You are already logged in.</h1>
  <h2>Log out First</h2>
</div>

{% else %}

<div class="formContainer container" style="margin-top: 50px">
  <div class="row justify-content-center">
    <div
      class="makeMiddle justify-content-center col-sm-12"
      style="display: inline"
    >
      <h1>Log in:</h1>
    </div>

    <form
      method="POST"
      class="justify-content-center text-align-center col-lg-8 col-md-12 col-sm-12"
      action="{% url 'userAuth:loginApp' %}"
    >
      <div
        class="message col-sm-12 justify-content-center"
        style="display: inline"
      >
        <h2 class="makeMiddle">{{ message }}</h2>
      </div>

      <div class="col-lg-8 col-md-10 col-sm-12" style="display: inline">
        <label for="username" style="float: left">User Name:</label>
        <input
          type="text"
          name="username"
          id="username"
          value="{{ username }}"
        />
      </div>

      <div class="col-lg-8 col-md-10 col-sm-12" style="display: inline">
        <label for="password" style="float: left">Password:</label>
        <input
          type="password"
          name="password"
          id="password"
          value=" {{ password }} "
        />
      </div>

      {% csrf_token %}

      <div class="makeMiddle justify-content-center mt-3 mb-3">
        <input type="submit" value="Login" />
      </div>
    </form>
  </div>
</div>

{% endif %} {% endblock %}

templates/authentication/registerUser.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block body_block %}

<style>
  .formContainer {
    min-height: 72.1vh;
    width: 70%;
  }
</style>

<div class="container" style="margin-top: 30px">
  <div class="makeMiddle mt-4">
    <a
      href="{% url 'dashboard:seeAllEmployee' %}"
      class="btn btn-outline-primary"
    >
      ⬅ Back</a
    >
  </div>

  {% if showMessage %}

  <div class="makeMiddle">
    <h1 style="margin-top: 30px">{{ message }}</h1>
  </div>

  {% else %}

  <div class="formContainer">
    <form method="POST" enctype="multipart/form-data">
      {{ userform.as_p }} {{ userform2.as_p }} {% csrf_token %}

      <div class="makeMiddle mt-4 mb-4">
        <input type="submit" value="register" />
      </div>
    </form>
  </div>

  {% endif %}
</div>

{% endblock %}