dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboardMainView , name='dashboard'),
    path('edit_profile/<int:id>/', views.editProfile , name='edit_profile'),
    path('createNotice/', views.createNotice , name='createNotice'),
    path('edit_notice/<int:id>/', views.editNotice , name='edit_notice'),
    path('make_complete/<int:id>/', views.makeComplete , name='make_complete'),
    path('make_incomplete/<int:id>/', views.makeIncomplete , name='make_incomplete'),
    path('delete_notice/<int:id>/', views.deleteNotice , name='delete_notice'),
    path('seeAllEmployee/', views.seeAllEmployee , name='seeAllEmployee'),
]

deals/urls.py
from django.urls import path
from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.dealsMainView , name='deals'),
    path('old_deals/', views.oldDeals , name='old_deals'),
    path('register_new_deal/', views.registerNewDeal , name='register_new_deal'),
    path('edit_deals/<int:id>/', views.editDeal , name='edit_deals'),
    path('terminate_or_end_deals/<int:id>/<str:endOrTerminate>/', views.terminateOrEndDeals , name='terminate_or_end_deals'),
    
]

finance/urls.py
from django.urls import path
from . import views

app_name = 'finance'

urlpatterns = [
    path('', views.seeSalary , name='see_salary'),
    path('see_salaries_in_details/', views.seeSalaryInDetails , name='see_salaries_in_details'),
    path('update_salary/', views.updateSalary , name='update_salary'),
    path('create_monthly_salary/', views.createSelaryStatus , name='create_monthly_salary'),
    path('make_employee_salary_paid/<int:id>', views.makeEmployeeSalaryPaid , name='make_employee_salary_paid'),
    path('accounts/', views.accountsMainView , name='accounts'),
    path('accounts_spend_money/', views.addSpendMoney , name='accounts_spend_money'),
    path('edit_spend_entry/<int:id>', views.editSpendMoney , name='edit_spend_entry'),
    path('edit_recived_entry/<int:id>', views.editRecivedMoney , name='edit_recived_entry'),
    path('delete_spend_entry/<int:id>', views.deleteSpendMoney , name='delete_spend_entry'),
    path('delete_recived_entry/<int:id>', views.deleteRecivedMoney , name='delete_recived_entry'),
    path('entity_register/', views.registerEntity , name='entity_register'),
    path('see_entity_to_edit/', views.seeAllEntry , name='see_entity_to_edit'),
    path('entity_edit/<int:id>', views.editEntity , name='entity_edit'),
    
]

minErp/urls.py
from django.contrib import admin
from django.urls import path, include

from userAuth import views

from django.conf import settings
from django.conf.urls import handler404
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('auth/', include('userAuth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('finance/', include('finance.urls')),
    path('deals/', include('deals.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'userAuth.views.notFound'

userAuth/urls.py
from django.urls import path
from . import views
from dashboard import views as dviews


app_name = 'userAuth'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', dviews.dashboardMainView, name='dashboard'),
    path('register/', views.userRegistration, name='userRegistation'),
    path('employee_delete/<int:id>', views.employeeDelete, name='employee_delete'),
    path('login/', views.loginApp, name='loginApp'),
    path('logout/', views.logoutApp, name='logoutApp'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Passions+Conflict&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- Latest compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'style/style.css' %}" />

    <link rel="icon" href="{% static 'images/icons/mainIcon.ico' %}" />

    {% block head_block %} {% endblock %}

    <title>Odvut Erp</title>
  </head>
  <body>
    <div class="loginRegistration">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'userAuth:index' %}">Home</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:seeAllEmployee' %}"
                >Employees</a
              >
            </li>

            {% if finaceController %}

            <li class="nav-item">
              <a href="{% url 'finance:see_salary' %}" class="nav-link"
                >Salaries</a
              >
            </li>

            <li class="nav-item">
              <a href="{% url 'finance:accounts' %}" class="nav-link"
                >Accounts</a
              >
            </li>

            {% endif %}

            <li class="nav-item">
              <a href="{% url 'deals:deals' %}" class="nav-link">Deals</a>
            </li>

            {% block nav_block %} {% endblock %}
          </ul>

          <form class="form-inline my-2 my-lg-0">
            <a
              href="{% url 'userAuth:logoutApp' %}"
              class="btn btn-success my-2 my-sm-0"
              >Log out</a
            >
          </form>

          {% else %}

          <form class="form-inline my-2 my-lg-0">
            <a
              href="{% url 'userAuth:loginApp' %}"
              class="btn btn-primary my-2 my-sm-0"
              >Log in</a
            >
          </form>
          {% endif %}
        </div>
      </nav>
    </div>

    <div class="wholeContainer">{% block body_block %} {% endblock %}</div>

    {% if user.is_authenticated %}

    <footer>
      <div class="container-fluid" style="background-color: black">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <div class="container">
            <div class="navbar navbar-right">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">Terms &amp; Conditions</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">Privacy Policy</a>
                </li>
              </ul>
            </div>

            <div class="navbar navbar-right">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="">
                    <img
                      src="{% static 'images/icons/web.png' %}"
                      alt="Website"
                      width="20px"
                    />
                  </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="">
                    <img
                      src="{% static 'images/icons/fb.png' %}"
                      alt="Facebook"
                      width="20px"
                    />
                  </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="">
                    <img
                      src="{% static 'images/icons/linkedin.png' %}"
                      alt="LinkedIn"
                      width="20px"
                    />
                  </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="">
                    <img
                      src="{% static 'images/icons/mail.png' %}"
                      alt="Mail"
                      width="20px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </footer>

    {% endif %}
  </body>
</html>

templates/showMessage.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block head_block %} {% endblock
%} {% block body_block %}

<style>
  .wrapper {
    min-height: 80vh;
    padding-top: 150px;
  }

  .margineTop100 {
    margin-top: 150px;
  }
</style>

<div class="container wrapper makeMiddle">
  {% if user.is_authenticated %} {% if message %}

  <h1 style="font-size: 3rem">{{ message }}</h1>

  {% else %}

  <h1 style="font-size: 3rem">Something went wrong</h1>

  {% endif %} {% endif %}
</div>

{% endblock %}