dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboardMainView , name='dashboard'),
    path('edit_profile/<int:id>/', views.editProfile , name='edit_profile'),
    path('createNotice/', views.createNotice , name='createNotice'),
    path('edit_notice/<int:id>/', views.editNotice , name='edit_notice'),
    path('make_complete/<int:id>/', views.makeComplete , name='make_complete'),
    path('make_incomplete/<int:id>/', views.makeIncomplete , name='make_incomplete'),
    path('delete_notice/<int:id>/', views.deleteNotice , name='delete_notice'),
    path('seeAllEmployee/', views.seeAllEmployee , name='seeAllEmployee'),
]

deals/urls.py
from django.urls import path
from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.dealsMainView , name='deals'),
    path('old_deals/', views.oldDeals , name='old_deals'),
    path('register_new_deal/', views.registerNewDeal , name='register_new_deal'),
    path('edit_deals/<int:id>/', views.editDeal , name='edit_deals'),
    path('terminate_or_end_deals/<int:id>/<str:endOrTerminate>/', views.terminateOrEndDeals , name='terminate_or_end_deals'),
    
]

minErp/urls.py
from django.contrib import admin
from django.urls import path, include

from userAuth import views

from django.conf import settings
from django.conf.urls import handler404
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('auth/', include('userAuth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('finance/', include('finance.urls')),
    path('deals/', include('deals.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'userAuth.views.notFound'

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from userAuth.models import userInfo

# Create your models here.

class notice(models.Model):

    user = models.ManyToManyField(userInfo)

    title = models.CharField(max_length=200)
    details = models.TextField()
    needToComplete = models.BooleanField(default=False)
    deadLine = models.DateField(blank=True, null=True)
    completedBy = models.CharField( max_length=10, blank=True)

dashboard/forms.py
from django import forms
from .models import notice
from userAuth import models


class addNotice(forms.ModelForm):

    deadLine = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}), required=False)
    class Meta():
        model = notice
        fields = ('user', 'title', 'details', 'needToComplete', 'deadLine')
        

    def __init__(self, *args, **kwargs): 
        super(forms.ModelForm, self).__init__(*args, **kwargs)

        self.css_class = "formInput"
        self.fields['user'].label = 'For Whom'
        self.fields['title'].label = 'Notice Title'
        self.fields['title'].widget.attrs = ({'type': 'password'})
        self.fields['details'].label = 'Notice Detailes'
        self.fields['needToComplete'].label = 'Is it a work that needs to be completed'




class editNotice(forms.ModelForm):
    
    deadLine = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}), required=False)
    class Meta():
        model = notice
        fields = ('user', 'title', 'details', 'needToComplete', 'deadLine', 'completedBy')

    def __init__(self, *args, **kwargs): 
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.css_class = "formInput"
        self.fields['user'].label = 'For Who'
        self.fields['title'].label = 'Notice Title'
        self.fields['details'].label = 'Notice Detailes'
        self.fields['needToComplete'].label = 'Is it a work that needs to be completed'

dashboard/views.py
from django.shortcuts import render

from userAuth.models import User, userInfo
from userAuth import models
from .models import notice

from .forms import addNotice, editNotice as editNotices
from userAuth.forms import userformMoreinfo, userform

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse



@login_required
def dashboardMainView(request):


    dict = {}

    if request.user.is_authenticated:

        currentUser = request.user

        dict.update({'myInfo' : currentUser})
        currentUserMoreInfo = userInfo.objects.get(user__pk = currentUser.id)
        dict.update({'myMoreInfo': currentUserMoreInfo})

        notices = notice.objects.filter(user=currentUserMoreInfo)
        dict.update({'notices': notices})


        if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "2"):

            notices = notice.objects.all()

            dict.update({'notices': notices})
            dict.update({"noticeController": True})


        if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "2" or currentUserMoreInfo.role == '3'):
            dict.update({"employeeController": True})
        
        
        if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "4"):
            dict.update({"finaceController": True})

        

    return render(request, 'dashboard/index.html', context=dict)





@login_required
def editProfile(request, id):

    currentUser = request.user
    currentUserMoreInfo = models.userInfo.objects.get(user__pk = currentUser.id)
    currentRole = currentUserMoreInfo.role

    userForm = userform(instance=currentUser)
    userForm2 = userformMoreinfo(instance=currentUserMoreInfo)

    dict = {'userform': userForm, 'userform2': userForm2, 'alertMessage': "Login back after changing personal data."}

    if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "2" or currentUserMoreInfo.role == "3" ):
        dict.update({"employeeController": True})

    if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "4" ):
        dict.update({"finaceController": True})
    
    if (currentUserMoreInfo.role == "1"):
        dict.update({"fullEmployeeControler": True})

        

    if (currentRole == '1') or (currentRole == '3'):
        currentUser = User.objects.get(pk=id)
        currentUserMoreInfo = models.userInfo.objects.get(user__pk = currentUser.id)
        currentRole = currentUserMoreInfo.role
        userForm = userform(instance=currentUser)
        userForm2 = userformMoreinfo(instance=currentUserMoreInfo)
        dict.update({"changeRole": True})
        dict.update({'userform': userForm})
        dict.update({'userform2': userForm2})


    if request.method == 'POST':

        userForm = userform(request.POST, instance=currentUser)
        userForm2 = userformMoreinfo(request.POST, instance=currentUserMoreInfo)

        if userForm.is_valid() and userForm2.is_valid():

            changedrole = userForm2.cleaned_data['role']

            requestUser = request.user
            requestUserMoreInfo = models.userInfo.objects.get(user__pk = requestUser.id)
            requestUserRole = requestUserMoreInfo.role

            if (changedrole != currentRole) and (requestUserRole != '1'):
                dict={'showMessage': True,'message': "You can not change role"}
                return render(request, 'showMessage.html', context=dict)
            
            
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            userInfo = userForm2.save(commit=False)
            userInfo.user = user

            if 'proPic' in request.FILES:
                userInfo.proPic = request.FILES['proPic']

            userInfo.save()


            if user.id == requestUser.id:
                return HttpResponseRedirect(reverse('userAuth:loginApp'))
            
            
            dict={'showMessage': True,'message': "Successfully Updated" }
            return render(request, 'showMessage.html', context=dict)
        
        dict={'showMessage': True,'message': "Invalid Submission."}
        return render(request, 'showMessage.html', context=dict)


    return render(request, 'authentication/editUser.html', context=dict)





@login_required
def createNotice(request):

    dict = {'btnText': "Add Notice"}

    currentUser = request.user
    currentUserMoreInfo = userInfo.objects.get(user__pk = currentUser.id)

    if (currentUserMoreInfo.role == "1") or (currentUserMoreInfo.role == "2"):
        
        createNotice = addNotice
        dict.update({"createNotice": createNotice})

        dict.update({"employeeController": True})
        
        if (currentUserMoreInfo.role == "1"):
            dict.update({"finaceController": True})

        if request.method == "POST":

            noticeForm = addNotice(data=request.POST)

            if noticeForm.is_valid():
                noticeForm.save()
                dict.update({'message': "Notice added successfully"})
                return render(request, 'showMessage.html', context=dict)
            else:
                noticeForm = addNotice(request.POST)
                dict.update({"createNotice": noticeForm})

            return HttpResponseRedirect(reverse('dashboard:dashboard'))

        dict.update({'check': True})
        return render(request, 'notices/createNotice.html', context=dict)
    

    dict.update({'message': "You do not have the authority to make a notice"})
    return render(request, 'showMessage.html', context=dict)




@login_required
def editNotice(request, id):

    dict = {'btnText': "Edit Notice"}

    currentUser = request.user
    currentUserMoreInfo = userInfo.objects.get(user__pk = currentUser.id)


    if (currentUserMoreInfo.role == "1") or (currentUserMoreInfo.role == "2"):
        
        getNotice = notice.objects.get(pk=id)
        noticeForm = editNotices(instance=getNotice)
        dict.update({"createNotice": noticeForm})

        users = models.User.objects.all()
        dict.update({"users": users})

        dict.update({"employeeController": True})
        
        if (currentUserMoreInfo.role == "1"):
            dict.update({"finaceController": True})

        if request.method == "POST":

            noticeForm = editNotices(request.POST, instance=getNotice)

            if noticeForm.is_valid():
                noticeForm.save()
                dict.update({'message': "Notice Updated successfully"})
                return HttpResponseRedirect(reverse('dashboard:dashboard'))
                
            else:
                noticeForm = editNotices(request.POST)
                dict.update({"createNotice": noticeForm})


        dict.update({'check': True})
        return render(request, 'notices/createNotice.html', context=dict)
    

    dict.update({'message': "You do not have the authority to edit a notice"})
    return render(request, 'showMessage.html', context=dict)



@login_required
def deleteNotice(request, id):

    dict = {}

    currentUser = request.user
    currentUserMoreInfo = userInfo.objects.get(user__pk = currentUser.id)


    if (currentUserMoreInfo.role == "1") or (currentUserMoreInfo.role == "2"):
        
        notice.objects.get(pk=id).delete()
        return HttpResponseRedirect(reverse('dashboard:dashboard'))
    
    dict.update({'message': "You do not have the authority to delete a notice"})
    return render(request, 'showMessage.html', context=dict)



@login_required
def makeComplete(request, id):

    currentUser = request.user
    
    getNotice = notice.objects.get(pk=id)
    
    if getNotice.completedBy:
        return HttpResponseRedirect(reverse('dashboard:dashboard'))
    
    
    getNotice.completedBy = currentUser.id
    getNotice.save(update_fields=['completedBy'])

    return HttpResponseRedirect(reverse('dashboard:dashboard'))



@login_required
def makeIncomplete(request, id):

    getNotice = notice.objects.get(pk=id)
    
    
    getNotice.completedBy = ""
    getNotice.save(update_fields=['completedBy'])

    return HttpResponseRedirect(reverse('dashboard:dashboard'))







@login_required
def seeAllEmployee(request):

    dict = {}

    currentUser = request.user
    currentUserMoreInfo = userInfo.objects.get(user__pk = currentUser.id)

    if currentUser.is_authenticated:

        users = User.objects.all()
        usersMoreInfo = userInfo.objects.order_by('role').select_related("user")

        dict.update({'users' : users})
        dict.update({'userMoreInfo': usersMoreInfo})

        if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "2" or currentUserMoreInfo.role == "3" ):
            dict.update({"employeeController": True})

        if (currentUserMoreInfo.role == "1" or currentUserMoreInfo.role == "4" ):
            dict.update({"finaceController": True})
        
        if (currentUserMoreInfo.role == "1"):
            dict.update({"fullEmployeeControler": True})

        return render(request, 'seeAllEmployee/allUserDetails.html', context=dict)
    
    dict.update({'message': "You does not have authority to see the employee"})
    return render(request, 'showMessage.html', context=dict)

templates/dashboard/index.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block nav_block %} {% endblock %}
{% block body_block %}

<style>
  /* .gridContainer{
    display: grid;
    grid-template-columns: 1fr 3fr;

} */

  .row {
    min-height: 75vh;
  }

  .info {
    text-align: center;
  }

  .proPic {
    width: 200px;
    height: 200px;
    overflow: hidden;
    object-fit: cover;
    border-radius: 10%;
  }

  .editDesign {
    cursor: pointer;
  }
</style>

{% if user.is_authenticated %}

<div
  class="gridContainer container"
  style="margin-top: 30px; margin-bottom: 30px"
>
  <div class="row">
    <div class="info col-lg-3 col-md-4 col-sm-12">
      <img
        src="/media/{{ myMoreInfo.proPic }}"
        alt="Profile Pic"
        class="proPic"
      />

      <h2>{{ myInfo.first_name }} {{ myInfo.last_name }}</h2>

      <p>
        {% if myMoreInfo.role == '1' %} ( Chief ) {% elif myMoreInfo.role == '2'
        %} ( Moderator ) {% elif myMoreInfo.role == '3' %} ( Human Resource ) {%
        elif myMoreInfo.role == '4' %} ( Accountant ) {% else %} ( Office
        Employee ) {% endif %}

        <a href="{% url 'dashboard:edit_profile' id=myInfo.id %}">
          <img
            src="{% static 'images/icons/edit.png' %}"
            alt="edit"
            width="15px"
          />
        </a>
      </p>

      <p>{{ myInfo.email }}</p>

      <a href="tel:{{ myMoreInfo.phone }}"> {{ myMoreInfo.phone }} </a>

      {% if noticeController %}

      <a href="{% url 'dashboard:createNotice' %}" class="buttonStyle2"
        >Add Notice</a
      >

      {% endif %}
    </div>

    <div class="notice col-lg-9 col-md-8 col-sm-12">
      {% if notices %} {% for note in notices %}

      <div class="notices">
        {% if note.needToComplete %} {% if note.completedBy %}
        <h1 style="color: #787878">{{ note.title }}</h1>
        <p style="color: #787878">{{ note.details }}</p>
        <h3 style="color: #787878">Dead line: {{ note.deadLine }}</h3>
        {% else %}
        <h1>{{ note.title }}</h1>
        <p>{{ note.details }}</p>
        <h5>
          Dead line: {{ note.deadLine }} {% now "Y-m-d" as todays_date %} {% if
          todays_date > note.deadLine|date:"Y-m-d" %}
          <span style="color: red"> ( Dead Line is Over ) </span>
          {% endif %}
        </h5>

        {% if noticeController %}

        <h5 style="display: inline-block">for:</h5>

        {% for user in note.user.all %}

        <h6 style="display: inline-block">{{ user }},</h6>

        {% endfor %} {% endif %} {% endif %} {% else %}

        <h1>{{ note.title }}</h1>
        <p>{{ note.details }}</p>

        {% endif %}

        <p>
          {% if noticeController %}

          <a
            href="{% url 'dashboard:edit_notice' id=note.id %}"
            class="buttonStyle1"
          >
            Edit
          </a>
          <a
            href="{% url 'dashboard:delete_notice' id=note.id %}"
            class="buttonStyle1"
            onclick="return confirm('Are you sure?')"
          >
            Delete
          </a>

          {% endif %} {% if note.needToComplete %} {% if note.completedBy %}
          <a
            href="{% url 'dashboard:make_incomplete' id=note.id %}"
            class="buttonStyle3"
            onclick="return confirm('Are you sure?')"
          >
            Undo
          </a>
          <span> Completed By: {{ note.completedBy }} </span>
          {% else %}

          <a
            href="{% url 'dashboard:make_complete' id=note.id %}"
            class="buttonStyle1"
            onclick="return confirm('Are you sure?')"
          >
            Complete
          </a>
          {% endif %} {% endif %}
        </p>

        <hr />
      </div>

      {% endfor %} {% else %}

      <h1>No notice available</h1>

      {% endif %}
    </div>
  </div>
</div>

{% endif %} {% endblock %}